Song.create(title: "The Best Song", released: true, release_year: 2018, artist_name: "Ryan The Shiz", genre: "Folk")
Song.create(title: "One and Only", released: false, release_year: 2020, artist_name: "Rolf Harris", genre: "Kids Music")
Song.create(title: "The Sound Of My Voice", released: true, release_year: 2015, artist_name: "Hypno Toad", genre: "Trance")
Song.create(title: "Enter The Void", released: false, release_year: 2021, artist_name: "Doc Dance", genre: "Electronic")
Song.create(title: "Spagetti Calling", released: false, release_year: 2021, artist_name: "Peter Sanfield", genre: "Classical")
Song.create(title: "Upon the Shore", released: true, release_year: 2018, artist_name: "Monty Ray", genre: "Carribean")
